### ISSUE TITLE
Build out dynamic behavior injection functionality

### ISSUE THREAD

**Issue by lambdahands** [webrecorder/browsertrix-behaviors#29]
## Overview

As part of a larger effort to support custom behaviors, developers as well as end users should have the ability to dynamically inject their own behaviors on a webpage. The library's functionality would be used by its consumers, namely the ArchiveWeb.page browser extension, to allow loading custom behaviors not part of the official library.

## Implementation

The `BehaviorManager` class is currently in charge of iterating through a static object [imported via the `src/site/index.js` module](https://github.com/webrecorder/browsertrix-behaviors/blob/1ba53cd84aeee50898dfba3bfaa5713c763cd494/src/index.js#L6). This class could be augmented to merge a separate object containing additional behaviors; this object would be modifiable by way of static methods on the `BehaviorManager` class.

## Challenges

This work partially relies on #31 in order to build a specific behavior into a separate output. Another challenge this work poses is the issue of security: there is need for discussion over how best to create "verifiable" behaviors.

**Comment by ikreymer** [comment]
Check with latest refactor

**Comment by ikreymer** [comment]
This is now part of 0.5.0 release!
The BehaviorManager has a `load` function for loading a single behavior class, and also `init()` supports a list of behaviors to be injected dynamically!
