### ISSUE TITLE
Write TikTokProfile behavior that leverages TikTokVideo behavior

### ISSUE THREAD

**Issue by lambdahands** [webrecorder/browsertrix-behaviors#30]
## Overview

After #27 is merged, the next step for crawling TikTok with behaviors is to setup a new `TikTokProfile` behavior class that targets profile pages.

## Implementation

This new class should leverage the `TikTokVideo` behavior class as it navigates between a profile page and each of its videos.

## Challenges

Similar challenges to the Twitter behavior may arise as the script navigates between multiple pages.

**Comment by ikreymer** [comment]
Will be in next Browsertrix-Crawler and ArchiveWeb.page release.
