### ISSUE TITLE
Allow for single-behavior builds

### ISSUE THREAD

**Issue by lambdahands** [webrecorder/browsertrix-behaviors#31]

**Comment by ikreymer** [comment]
As discussed, I think plan is we'd create a new template repo, `browsertrix-single-behavior` that then would already have a template, something like:

```
import {Behavior, utils} from "browsertrix-behaviors"

class MyBehavior extends Behavior
{
   async* [Symbol.asyncIterator]() {
     ...
  }
}
```

and be configured to build correctly using webpack / rollup.

Then, in this repo, we would ensure that we have a `loadExtensionBehavior("my-extension-behavior.js")` function that can load the output of each of these template behaviors.

That should probably be a good start?

**Comment by ikreymer** [comment]
Behaviors can now be loaded dynamically, with no external dependencies, so no longer need custom builds for behaviors!
