### ISSUE TITLE
Automated CI build

### ISSUE THREAD

**Issue by Chickensoupwithrice** [webrecorder/browsertrix-behaviors#61]
Currently the CI doesn't run `yarn build`, it should do that!

**Comment by ikreymer** [comment]
yes, perhaps the lint workflow can be renamed to lint_and_build and add yarn build there as well?

**Comment by Chickensoupwithrice** [comment]
great idea

**Comment by Chickensoupwithrice** [comment]
With the merge of #65 this is complete
