### ISSUE TITLE
New Behavior Request to retrieve automatically the assets present in a data-xxx tag 

### ISSUE THREAD

**Issue by benoit74** [webrecorder/browsertrix-behaviors#72]
**What website should this before be applied to?**

Many, but for instance https://solar.lowtechmagazine.com/

**Is this a well known site that often needs to be archived?**

Yep, at least from openZIM PoV

**Describe in detail what the automated behavior should do. Please be as specific as possible.**

See https://github.com/openzim/zimit/issues/316 for details

**Do you have the ability/bandwidth to contribute a pull request to implement this behavior?**

Yep, would be happy to contribute the PR if implementing this behavior in browsertrix would make sense to you

**Comment by benoit74** [comment]
I'm starting to work on this behavior

**Comment by ikreymer** [comment]
> I'm starting to work on this behavior

Thanks, sorry, missed this issue earlier! I think it would be simplest just to add this to the autofetcher.ts behavior, as it already designed for this, queries different selectors, etc.. instead of making a new behavior. Seems like the idea is just to check for any data-* and see if its an absolute URL, right?

**Comment by benoit74** [comment]
No worries, and thank you.

I came to the same conclusion no that I had a look at the existing codebase ^^ I don't want to duplicate all this effort around the processing queue, non-cors fetch, ...

I'm just a bit concerned about the impact this modification might have, since it will be either all "autofetch" or nothing, and autofetch is enabled by default.

I consider to include any relative or absolute URL, or more precisely anything starting with `http` or `/` or `./` or `../` ; obviously we will have some stuff which is not really a URL, but I consider chances are relatively moderate and this should just create "fake" 404 WARC records, isn't it?

Our first use-case is this website: https://solar.lowtechmagazine.com/2024/03/how-to-escape-from-the-iron-age/ where they use the `data-dither` and `data-original` attribute to store image "variants". And urls here either start with `http` or `/`.
